# Generated by Django 4.2.30 on 2026-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='user_id',
            field=models.CharField(db_index=True, default='guest', max_length=128),
        ),
    ]
