# Generated by Django 4.2.30 on 2026-08-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_counselingsession_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(help_text='ユーザーID (一意)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='名前 / 表示名', max_length=128)),
                ('password', models.CharField(help_text='パスワード', max_length=256)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
