# Generated by Django 5.2.4 on 2026-09-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='element',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='response_type',
            field=models.CharField(blank=True, choices=[('answer', '回答'), ('dont_know', '思いつかない'), ('nothing', '特にない')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('failure', '失敗経験'), ('related', '関連経験')], max_length=16)),
                ('relation_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('action', models.TextField(blank=True, default='')),
                ('pre_states', models.JSONField(blank=True, default=list)),
                ('post_states', models.JSONField(blank=True, default=list)),
                ('pre_thought', models.TextField(blank=True, default='')),
                ('post_thought', models.TextField(blank=True, default='')),
                ('pre_state_and_action', models.TextField(blank=True, default='')),
                ('evaluation', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='counseling.counselingsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecallSupportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=32)),
                ('element', models.CharField(max_length=64)),
                ('attempt', models.PositiveIntegerField()),
                ('prompt', models.TextField()),
                ('raw_output', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_support_logs', to='counseling.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_support_logs', to='counseling.counselingsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
